Style/HashSyntax:
  Enabled: false

Metrics/LineLength:
  Max: 132

Style/UnneededInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

#Style/StringLiteralsInInterpolation:
#  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/EmptyLiteral:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 15

Style/SpaceInsideBrackets:
  Enabled: false
